Proyecto2_ChangOleaAngel/clinico/appbase/urls.py
from django.urls import path
from .views import *
app_name = 'base'
urlpatterns = [
#PACIENTE
    path('paciente/', PacienteView.as_view(), name='paciente'),
    path('crear_paciente/', CrearPacienteView.as_view(), name='crear_paciente'),
    path('editar_paciente/<int:pk>/',
         EditarPacienteView.as_view(), name='editar_paciente'),
    path('eliminar_paciente/<int:pk>/',
         EliminarPacienteView.as_view(), name='eliminar_paciente'),
#DOCTOR
    path('doctor/', DoctorView.as_view(), name='doctor'),
    path('registrar_doctor/', CrearDoctorView.as_view(), name='registrar_doctor'),
    path('editar_doctor/<int:pk>/',
         EditarDoctorView.as_view(), name='editar_doctor'),
    path('eliminar_doctor/<int:pk>/',
         EliminarDoctorView.as_view(), name='eliminar_doctor'),
#HORARIO
    path('horario/',ListadoHorarioView.as_view(), name='horario'),
    path('registrar_horario/', CrearHorarioView.as_view(),name='registrar_horario'),
    path('eliminar_horario/<int:pk>/', EliminarHorarioView.as_view(),name='eliminar_horario'),
    path('editar_horario/<int:pk>/', EditarHorarioView.as_view(),name='editar_horario'),
#CITAS
    path('cita/',ListadoCitaView.as_view(), name='cita'),
    path('registrar_cita/', CrearCitaView.as_view(),name='registrar_cita'),
    path('eliminar_cita/<int:pk>/', EliminarCitaView.as_view(),name='eliminar_cita'),
    path('editar_cita/<int:pk>/', EditarCitaView.as_view(),name='editar_cita'),
#SIGNO VITAL
    path('signoVital/',ListadoSigVitalView.as_view(), name='signoVital'),
    path('registrar_signoVital/', CrearSigVitalView.as_view(),name='registrar_signoVital'),
    path('eliminar_signoVital/<int:pk>/', EliminarSigVitalView.as_view(),name='eliminar_signoVital'),
    path('editar_signoVital/<int:pk>/', EditarSigVitalView.as_view(),name='editar_signoVital'),
]

Proyecto2_ChangOleaAngel/clinico/templates/base/cita/listar_cita.html
{% extends 'base.html' %}
{% block header %}
{% include 'header.html' %}
{% endblock %}
{% block main %}
{% load static %}
<div class="container-fluid" style="margin-top: 3rem;">
    <div class="card">
        <div class="card-header bg-success text-light ">
            <div class="row">
                <div class="col-md-8">
                    <h3 id="titulo" class="font-weight-bold" onclick="convertir()">Consulta de Citas</h3>
                </div>
                <div class="col-md-4 ">
                    <a href="{% url 'base:registrar_cita' %}" class="btn btn-primary float-right">Nuevo Registro</a>
                </div>
            </div>
        </div>
        <div class="card-body table-responsive">
            <div class="row">
                
            </div>
            <div class="row pt-2">
                <div class="col">
                    <table class="table table-striped table-hover table-sm">
                        <thead>
                            <tr>
                                <th class="text-center">Paciente</th>
                                <th class="text-center">Fecha de Agenda</th>
                                <th class="text-center">Hora</th>
                                <th class="text-center">Motivo Consulta</th>
                                <th class="text-center">Estado</th>
                                <th class="text-center">Acciones</th>
                            </tr>

                        </thead>
                        <tbody id="tabla">
                            {% for agenda in agendas%}
                            <tr>
                                <td class="text-center">{{ agenda.paciente.nombre }}</td>
                                <td class="text-center">{{ agenda.fecha }}</td>
                                <td class="text-center">{{ agenda.hora }}</td>
                                <td class="text-center">{{ agenda.motivo }}</td>
                                {% if agenda.estado %}
                                  <td class="text-center"><samp class="badge 
                                        badge-pill badge-primary">Activo</samp></td>
                                {% else %}
                                   <td class="text-center"><samp class="badge 
                                        badge-pill badge-danger">Deshuso</samp></td>
                                {% endif %}
                                <td class="text-center"><a class="btn btn-primary btn-sm"
                                    href="{% url 'base:editar_cita' agenda.id %}">Editar</a>
                                    <a rel="action" data-json='{"accion":"elim" ,"id":"{{agenda.id}}"}'
                                        class="btn btn-danger btn-sm" href="#">Eliminar</a>
                                </td>
                            </tr>
                            {% empty %}
                            <div class="alert alert-warning alert-dismissible fade show mt-2" role="alert">
                                <strong>Mensaje del Sistema!</strong> No existen citas registradas
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <!--Mensaje de error cuando no puede borrar-->
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <script>
                    alert('{{ message }}');
                </script>
                {% endfor %}
            </ul>
            {% endif %}
            <!-- Menú de paginación -->
            {% if is_paginated %}
            <nav aria-label="Page navigation">
                <ul class="pagination justify-content-center">
                    {% if page_obj.has_previous %}
                    <li class="page-item ">
                        <a class="page-link"
                            href="?nombre={{nombre}}&page={{ page_obj.previous_page_number }}">&laquo;</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1">&laquo;</a>
                    </li>
                    {% endif %}
                    {% for i in paginator.page_range %}
                    {% if i <= page_obj.number|add:2 and i >= page_obj.number|add:-2 %}
                    {% if page_obj.number == i %}
                    <li class="page-item active" style="pointer-events:none">
                        <a href="#" class="page-link">{{ forloop.counter }}</a>
                    </li>
                    {% else %}
                    <li class="page-item">
                        <a href="?page={{ forloop.counter }}{{ url }}" class="page-link">{{ forloop.counter }}</a>
                    </li>
                    {% endif %}
                    {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                    <li class="page-item ">
                        <a class="page-link" href="?nombre={{nombre}}&page={{ page_obj.next_page_number }}">&raquo;</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1">&raquo;</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
            {% endif %}
            <!-- Fin del pagineo -->
        </div>
    </div>



</div>
{% endblock %}

{% block frmodal %}
<!-- inicio formulario Modal para Eliminar -->

<div class="modal fade" id="myModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <form name="frmEliminar" id="frmEliminar" method="POST" action="{% url 'base:eliminar_cita' 0 %} ">
                {% csrf_token %}
                <div class="modal-header bg-primary text-light">
                    <h3 class="modal-title ml-5 font-weight-bold">Mensaje Del Sistema</h3>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <input type="hidden" name="id" id="id" value="">
                    <input type="hidden" name="action" value="elim">
                    <div class="h3 text-center">
                        <label class="text-primary font-weight-bold">Esta Seguro De Eliminar La Cita:</label>
                        <span class="text-light font-weight-bold badge badge-danger badge-pill"
                            id="descripcion"></span><br>

                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Eliminar</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- Final Formulario Modal-->
{% endblock %}

{% block jscript %}
<script>
    $(function () {

        $('#tabla').on('click', 'a[rel="action"]', function () {
            let data = $(this).data('json'),
                action = data.accion,
                id = data.id;
            let desc = $(this).parents('tr').children('td').eq(0).html();
            $('#descripcion').html(desc);
            $('#frmEliminar #id').val(id);
            $('#myModal').modal('show');
            return;

        });

    })

    function convertir() {
        let titulo = document.getElementById("titulo").innerText
        document.getElementById("titulo").innerText = titulo.toUpperCase()
        alert(titulo)
    }
</script>
{% endblock %}

Proyecto2_ChangOleaAngel/clinico/templates/base/cita/registrar_cita.html
{% extends 'base.html' %}
{% block header %}
{% include 'header.html' %}
{% endblock %}
{% block main %}
{% load static %}
<div class="container-fluid" style="margin-top: 3rem;">
    <div class="card">
        <div class="card-header bg-success text-light ">
            <div class="row">
                <div class="col-md-8">
                    <h3 class="font-weight-bold">Mantenimiento de Citas</h3>
                </div>
                <div class="col-md-4 ">
                    <a href="{% url 'base:cita' %}" class="btn btn-primary float-right">Cancelar</a>
                </div>
            </div>
        </div>
        <div class="card-body">
            <div class="col-md-12">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <!-- {{ form.as_p }} -->
                    <!-- <div class="form-group row">
                        <label class="col-sm-2 col-form-label"
                            for="id_{{ form.nombre.name }}">{{form.nombre.label}}</label>
                        <div class="col-sm-4>
                            {{form.nombre}} 
                        </div>
                        <label class="col-sm-2 col-form-label"
                            for="id_{{ form.apellido.name }}">{{form.apellido.label}}</label>
                        <div class="col-sm-4>
                            {{form.apellido}} 
                        </div>

                    </div> -->
                    {% if form.errors %}
                    <div class="alert alert-warning alert-dismissible fade show mt-2" role="alert">
                        <strong> {{ form.errors}}</strong>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    {% endif %}
                    {% for campo in form %}
                    <div class="form-group row">
                        <label class="col-md-2 col-form-label" for="id_{{ campo.name }}">{{campo.label}}</label>
                        <div class="col-md-10">
                            {{campo}}
                        </div>
                    </div>
                    {% endfor %}
                    <button class="btn btn-success btn-block" type="submit">Registrar</button>

                </form>
            </div>


        </div>
    </div>

</div>
{% endblock %}

{% block jscript %}
<script>
    $(function () {


    })

</script>
{% endblock %}