Proyecto2_ChangOleaAngel/clinico/appbase/urls.py
from django.urls import path
from .views import *
app_name = 'base'
urlpatterns = [
#PACIENTE
    path('paciente/', PacienteView.as_view(), name='paciente'),
    path('crear_paciente/', CrearPacienteView.as_view(), name='crear_paciente'),
    path('editar_paciente/<int:pk>/',
         EditarPacienteView.as_view(), name='editar_paciente'),
    path('eliminar_paciente/<int:pk>/',
         EliminarPacienteView.as_view(), name='eliminar_paciente'),
#DOCTOR
    path('doctor/', DoctorView.as_view(), name='doctor'),
    path('registrar_doctor/', CrearDoctorView.as_view(), name='registrar_doctor'),
    path('editar_doctor/<int:pk>/',
         EditarDoctorView.as_view(), name='editar_doctor'),
    path('eliminar_doctor/<int:pk>/',
         EliminarDoctorView.as_view(), name='eliminar_doctor'),
#HORARIO
    path('horario/',ListadoHorarioView.as_view(), name='horario'),
    path('registrar_horario/', CrearHorarioView.as_view(),name='registrar_horario'),
    path('eliminar_horario/<int:pk>/', EliminarHorarioView.as_view(),name='eliminar_horario'),
    path('editar_horario/<int:pk>/', EditarHorarioView.as_view(),name='editar_horario'),
#CITAS
    path('cita/',ListadoCitaView.as_view(), name='cita'),
    path('registrar_cita/', CrearCitaView.as_view(),name='registrar_cita'),
    path('eliminar_cita/<int:pk>/', EliminarCitaView.as_view(),name='eliminar_cita'),
    path('editar_cita/<int:pk>/', EditarCitaView.as_view(),name='editar_cita'),
#SIGNO VITAL
    path('signoVital/',ListadoSigVitalView.as_view(), name='signoVital'),
    path('registrar_signoVital/', CrearSigVitalView.as_view(),name='registrar_signoVital'),
    path('eliminar_signoVital/<int:pk>/', EliminarSigVitalView.as_view(),name='eliminar_signoVital'),
    path('editar_signoVital/<int:pk>/', EditarSigVitalView.as_view(),name='editar_signoVital'),
]

Proyecto2_ChangOleaAngel/clinico/appconsulta/urls.py
from django.urls import path
from .views import *

app_name = "atencion"
urlpatterns = [
    path('historia/', HistoriaView2.as_view(), name='historia'),
    #RECETA
    path('recetas/', RecetasPacientes.as_view(), name='recetas'),
    path('registrar_receta/', NuevaRecetaPacientes.as_view(), name='registrar_receta'),
    #DETALLE RECETA
    path('registrar_detReceta/',DetalleRecetaPacientes.as_view(), name='registrar_detReceta'),
    path('detReceta/',DetalleRecetas.as_view(), name='detReceta'),
    #SIGNO VITAL
    path('toSigno/',SignosPacientes.as_view(), name='toSigno'),
    path('registrar_toSigno/',TomaSignosPacientes.as_view(), name='registrar_toSigno')
]

Proyecto2_ChangOleaAngel/clinico/templates/atencion/receta/detalleReceta.html
{% extends 'base.html' %}
{% block header %}
{% include 'header.html' %}
{% endblock %}
{% block main %}
{% load static %}
<div class="container-fluid" style="margin-top: 3rem;">
    <div class="card">
        <div class="card-header bg-success text-light ">
            <div class="row">
                <div class="card-title col-md-8 mt-2">
                    <h2 class="font-weight-bold">
                        Consulta de Detalle Receta 
                    </h2>
                </div>
                <div class="col-md-4">
                    <div class="float-right m-3">
                        <a class="btn btn-primary btn-sm"
                        href="{% url 'atencion:registrar_detReceta' %}?id_rec={{detRecetas.receta.id}}">Nuevo Detalle</a>
                        {% comment %} <a class="btn btn-primary btn-sm" href="{% url 'atencion:detalle' %}?id_paciente={{recetas.paciente.id}}">Detalle de Receta</a>
                        <a class="btn btn-primary btn-sm" href="{% url 'atencion:toma' %}">Toma de Signos</a> {% endcomment %}
                        <a class="btn btn-primary btn-sm" href="{% url 'base:paciente' %}">Cancelar</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-body table-responsive">
            
            <div class="row pt-2">
                <div class="col">
                    <table class="table table-striped table-hover table-sm  ">

                        <thead>
                            <tr>
                                <th class="text-center">Receta</th>
                                <th class="text-center">Medicamento</th>
                                <th class="text-center">Cantidad</th>
                                <th class="text-center">Dosis</th>
                                <th class="text-center">Frecuencias</th>
                                <th class="text-center">Duracion</th>
                            </tr>

                        </thead>
                        <tbody id="tabla">
                            {% for rec in detRecetas%}
                            <tr>
                                <td class="text-center">{{ rec.receta }}</td>
                                <td class="text-center">{{ rec.medicamento.descripcion }}</td>
                                <td class="text-center">{{ rec.cantidad }}</td>
                                <td class="text-center">{{ rec.dosis.descripcion }}</td>
                                <td class="text-center">{{ rec.frecuencia.descripcion }}</td>
                                <td class="text-center">{{ rec.duracion.descripcion }}</td>
                            </tr>
                            {% empty %}
                            <div class="alert alert-warning alert-dismissible fade show mt-2" role="alert">
                                <strong>Mensaje del Sistema!</strong> No Existen Detalles Registrados de esta Receta.
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Proyecto2_ChangOleaAngel/clinico/templates/atencion/receta/receta.html
{% extends 'base.html' %}
{% block header %}
{% include 'header.html' %}
{% endblock %}
{% block main %}
{% load static %}
<div class="container-fluid" style="margin-top: 3rem;">
    <div class="card">
        <div class="card-header bg-success text-light ">
            <div class="row">
                <div class="card-title col-md-8 mt-2">
                    <h2 class="font-weight-bold">
                        Consulta de Recetas del paciente 
                    </h2>
                </div>
                <div class="col-md-4">
                    <div class="float-right m-3">
                        <a class="btn btn-primary btn-sm"
                        href="{% url 'atencion:registrar_receta' %}?id_paciente={{recetas.paciente.id}}">Nueva Receta</a>
                        {% comment %} <a class="btn btn-primary btn-sm" href="{% url 'atencion:detalle' %}?id_paciente={{recetas.paciente.id}}">Detalle de Receta</a>
                        <a class="btn btn-primary btn-sm" href="{% url 'atencion:toma' %}">Toma de Signos</a> {% endcomment %}
                        <a class="btn btn-primary btn-sm" href="{% url 'base:paciente' %}">Cancelar</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-body table-responsive">
            
            <div class="row pt-2">
                <div class="col">
                    <table class="table table-striped table-hover table-sm  ">

                        <thead>
                            <tr>
                                <th class="text-center">Paciente</th>
                                <th class="text-center">Fecha</th>
                                <th class="text-center">Hora</th>
                                <th class="text-center">Motivo</th>
                                <th class="text-center">Acciones</th>
                            </tr>

                        </thead>
                        <tbody id="tabla">
                            {% for rec in recetas%}
                            <tr>
                                <td class="text-center">{{ rec.paciente.nombre }}</td>
                                <td class="text-center">{{ rec.fecha }}</td>
                                <td class="text-center">{{ rec.hora }}</td>
                                <td class="text-center">{{ rec.motivo }}</td>
                                <td class="text-center"><a class="btn btn-primary btn-sm" href="{% url 'atencion:detReceta' %}?id_rec={{rec.id}}">Detalle de esta Receta</a>
                                    <a class="btn btn-primary btn-sm" href="{% url 'atencion:toSigno' %}?id_rec={{rec.id}}">Signos Vitales</a></td>
                            </tr>
                            {% empty %}
                            <div class="alert alert-warning alert-dismissible fade show mt-2" role="alert">
                                <strong>Mensaje del Sistema!</strong> No existen Recetas del paciente registradas.
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Proyecto2_ChangOleaAngel/clinico/templates/atencion/receta/registrar_detalleReceta.html
{% extends 'base.html' %}
{% block header %}
{% include 'header.html' %}
{% endblock %}

{% block main %}
{% load static %}
<div class="container-fluid" style="margin-top: 3rem">
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-herader rounded-top bg-success shadow p-0">
                    <div class="row">
                        <div class="card-title col-md-8 mt-2">
                            <h2 class="text-light ml-2 font-italic font-weight-bold">
                                Mantenimiento De Detalle de Receta 
                            </h2>
                        </div>
                        <div class="col-md-4">
                            <div class="float-right m-3">
                                <a href="{% url 'base:paciente' %}" class="btn btn-primary">
                                    Cancelar
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                            <form method="POST">
                                {% csrf_token %}
                                {{ form.as_p }}

                                <button class="btn btn-success btn-block"
                                type="submit">Registrar</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

Proyecto2_ChangOleaAngel/clinico/templates/atencion/receta/registrar_receta.html
{% extends 'base.html' %}
{% block header %}
{% include 'header.html' %}
{% endblock %}

{% block main %}
{% load static %}
<div class="container-fluid" style="margin-top: 3rem">
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-herader rounded-top bg-success shadow p-0">
                    <div class="row">
                        <div class="card-title col-md-8 mt-2">
                            <h2 class="text-light ml-2 font-italic font-weight-bold">
                                Mantenimiento De Recetas 
                            </h2>
                        </div>
                        <div class="col-md-4">
                            <div class="float-right m-3">
                                <a href="{% url 'base:paciente' %}" class="btn btn-primary">
                                    Cancelar
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                            <form method="POST">
                                {% csrf_token %}
                                {{ form.as_p }}

                                <button class="btn btn-success btn-block"
                                type="submit">Registrar</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

Proyecto2_ChangOleaAngel/clinico/templates/atencion/receta/registrar_tomaSigVitales.html
{% extends 'base.html' %}
{% block header %}
{% include 'header.html' %}
{% endblock %}

{% block main %}
{% load static %}
<div class="container-fluid" style="margin-top: 3rem">
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-herader rounded-top bg-success shadow p-0">
                    <div class="row">
                        <div class="card-title col-md-8 mt-2">
                            <h2 class="text-light ml-2 font-italic font-weight-bold">
                                Mantenimiento De Toma de Signos Vitales
                            </h2>
                        </div>
                        <div class="col-md-4">
                            <div class="float-right m-3">
                                <a href="{% url 'base:paciente' %}" class="btn btn-primary">
                                    Cancelar
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                            <form method="POST">
                                {% csrf_token %}
                                {{ form.as_p }}

                                <button class="btn btn-success btn-block"
                                type="submit">Registrar</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

Proyecto2_ChangOleaAngel/clinico/templates/atencion/receta/tomaSigVitales.html
{% extends 'base.html' %}
{% block header %}
{% include 'header.html' %}
{% endblock %}
{% block main %}
{% load static %}
<div class="container-fluid" style="margin-top: 3rem;">
    <div class="card">
        <div class="card-header bg-success text-light ">
            <div class="row">
                <div class="card-title col-md-8 mt-2">
                    <h2 class="font-weight-bold">
                        Consulta de signoetas del paciente 
                    </h2>
                </div>
                <div class="col-md-4">
                    <div class="float-right m-3">
                        <a class="btn btn-primary btn-sm"
                        href="{% url 'atencion:registrar_toSigno' %}?id_signo={{signos.signoeta.id}}">Nueva Toma de SignoVital</a>
                        {% comment %} <a class="btn btn-primary btn-sm" href="{% url 'atencion:detalle' %}?id_paciente={{signoetas.paciente.id}}">Detalle de signoeta</a>
                        <a class="btn btn-primary btn-sm" href="{% url 'atencion:toma' %}">Toma de Signos</a> {% endcomment %}
                        <a class="btn btn-primary btn-sm" href="{% url 'base:paciente' %}">Cancelar</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-body table-responsive">
            
            <div class="row pt-2">
                <div class="col">
                    <table class="table table-striped table-hover table-sm  ">

                        <thead>
                            <tr>
                                <th class="text-center">Receta</th>
                                <th class="text-center">Signo Vital</th>
                                <th class="text-center">Valor</th>
                            </tr>

                        </thead>
                        <tbody id="tabla">
                            {% for signo in signos%}
                            <tr>
                                <td class="text-center">{{ signo.receta }}</td>
                                <td class="text-center">{{ signo.signovital.descripcion }}</td>
                                <td class="text-center">{{ signo.valor }} {{signo.signovital.medida}}</td>
                            </tr>
                            {% empty %}
                            <div class="alert alert-warning alert-dismissible fade show mt-2" role="alert">
                                <strong>Mensaje del Sistema!</strong> No existen Signos Vitales del Paciente registrados.
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}